stages:
  - name: helloworld
    dependencies: [init]
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        sleeptime: {stages: init, output: sleeptime, unwrap: True}
        inputsdir: '{workdir}/../inputs'
        codedir: '{workdir}/../code'
        # We don't write to {workdir}/../greetings.txt because this is mounted as RO inside docker
        outputfile: '{workdir}/greetings.txt'
      step:
        process:
          process_type: 'string-interpolated-cmd'
          cmd: 'python {codedir}/helloworld.py --sleeptime {sleeptime} --outputfile {outputfile} --inputfile {inputsdir}/names.txt'
        publisher:
          publisher_type: 'frompar-pub'
          outputmap:
            outputfile: outputfile
        environment:
          environment_type: 'docker-encapsulated'
          image: 'python'
          imagetag: '2.7'
